/* tslint:disable */
/* eslint-disable */
/**
 * 南师教室
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 教室列表
 * @export
 * @interface ClassroomItemVo
 */
export interface ClassroomItemVo {
    /**
     * 教学楼名称
     * @type {string}
     * @memberof ClassroomItemVo
     */
    jxlmc: string;
    /**
     * 教室门牌号
     * @type {string}
     * @memberof ClassroomItemVo
     */
    jsmph?: string;
    /**
     * 教室代码
     * @type {string}
     * @memberof ClassroomItemVo
     */
    jasdm: string;
}

export function ClassroomItemVoFromJSON(json: any): ClassroomItemVo {
    return ClassroomItemVoFromJSONTyped(json, false);
}

export function ClassroomItemVoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClassroomItemVo {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'jxlmc': json['jxlmc'],
        'jsmph': !exists(json, 'jsmph') ? undefined : json['jsmph'],
        'jasdm': json['jasdm'],
    };
}

export function ClassroomItemVoToJSON(value?: ClassroomItemVo | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'jxlmc': value.jxlmc,
        'jsmph': value.jsmph,
        'jasdm': value.jasdm,
    };
}


