/* tslint:disable */
/* eslint-disable */
/**
 * 南师教室
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ClassroomItemVo,
    ClassroomItemVoFromJSON,
    ClassroomItemVoFromJSONTyped,
    ClassroomItemVoToJSON,
} from './index';

/**
 * 教室信息
 * @export
 * @interface ClassroomVo
 */
export interface ClassroomVo {
    /**
     * 教学楼名称
     * @type {string}
     * @memberof ClassroomVo
     */
    jxlmc: string;
    /**
     * 教室列表
     * @type {Array<ClassroomItemVo>}
     * @memberof ClassroomVo
     */
    list: Array<ClassroomItemVo>;
}

export function ClassroomVoFromJSON(json: any): ClassroomVo {
    return ClassroomVoFromJSONTyped(json, false);
}

export function ClassroomVoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClassroomVo {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'jxlmc': json['jxlmc'],
        'list': ((json['list'] as Array<any>).map(ClassroomItemVoFromJSON)),
    };
}

export function ClassroomVoToJSON(value?: ClassroomVo | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'jxlmc': value.jxlmc,
        'list': ((value.list as Array<any>).map(ClassroomItemVoToJSON)),
    };
}


