/* tslint:disable */
/* eslint-disable */
/**
 * 南师教室
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    GridVo,
    GridVoFromJSON,
    GridVoFromJSONTyped,
    GridVoToJSON,
} from './';

/**
 * 
 * @export
 * @interface CommonResultListGridVo
 */
export interface CommonResultListGridVo {
    /**
     * 状态码
     * @type {number}
     * @memberof CommonResultListGridVo
     */
    status: number;
    /**
     * 错误信息
     * @type {string}
     * @memberof CommonResultListGridVo
     */
    message: string | null;
    /**
     * 
     * @type {Array<GridVo>}
     * @memberof CommonResultListGridVo
     */
    data: Array<GridVo> | null;
}

export function CommonResultListGridVoFromJSON(json: any): CommonResultListGridVo {
    return CommonResultListGridVoFromJSONTyped(json, false);
}

export function CommonResultListGridVoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommonResultListGridVo {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'status': json['status'],
        'message': json['message'],
        'data': (json['data'] === null ? null : (json['data'] as Array<any>).map(GridVoFromJSON)),
    };
}

export function CommonResultListGridVoToJSON(value?: CommonResultListGridVo | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'status': value.status,
        'message': value.message,
        'data': (value.data === null ? null : (value.data as Array<any>).map(GridVoToJSON)),
    };
}


