/* tslint:disable */
/* eslint-disable */
/**
 * 南师教室
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ClassroomVo,
    ClassroomVoFromJSON,
    ClassroomVoFromJSONTyped,
    ClassroomVoToJSON,
} from './';

/**
 * 
 * @export
 * @interface CommonResultListClassroomVo
 */
export interface CommonResultListClassroomVo {
    /**
     * 状态码
     * @type {number}
     * @memberof CommonResultListClassroomVo
     */
    status: number;
    /**
     * 错误信息
     * @type {string}
     * @memberof CommonResultListClassroomVo
     */
    message: string | null;
    /**
     * 
     * @type {Array<ClassroomVo>}
     * @memberof CommonResultListClassroomVo
     */
    data: Array<ClassroomVo> | null;
}

export function CommonResultListClassroomVoFromJSON(json: any): CommonResultListClassroomVo {
    return CommonResultListClassroomVoFromJSONTyped(json, false);
}

export function CommonResultListClassroomVoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommonResultListClassroomVo {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'status': json['status'],
        'message': json['message'],
        'data': (json['data'] === null ? null : (json['data'] as Array<any>).map(ClassroomVoFromJSON)),
    };
}

export function CommonResultListClassroomVoToJSON(value?: CommonResultListClassroomVo | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'status': value.status,
        'message': value.message,
        'data': (value.data === null ? null : (value.data as Array<any>).map(ClassroomVoToJSON)),
    };
}


