/* tslint:disable */
/* eslint-disable */
/**
 * 南师教室
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CommonResultBoolean
 */
export interface CommonResultBoolean {
    /**
     * 状态码
     * @type {number}
     * @memberof CommonResultBoolean
     */
    status: number;
    /**
     * 错误信息
     * @type {string}
     * @memberof CommonResultBoolean
     */
    message: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof CommonResultBoolean
     */
    data: boolean | null;
}

export function CommonResultBooleanFromJSON(json: any): CommonResultBoolean {
    return CommonResultBooleanFromJSONTyped(json, false);
}

export function CommonResultBooleanFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommonResultBoolean {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'status': json['status'],
        'message': json['message'],
        'data': json['data'],
    };
}

export function CommonResultBooleanToJSON(value?: CommonResultBoolean | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'status': value.status,
        'message': value.message,
        'data': value.data,
    };
}


