/* tslint:disable */
/* eslint-disable */
/**
 * 南师教室
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    PositionVo,
    PositionVoFromJSON,
    PositionVoFromJSONTyped,
    PositionVoToJSON,
} from './';

/**
 * 
 * @export
 * @interface CommonResultListPositionVo
 */
export interface CommonResultListPositionVo {
    /**
     * 状态码
     * @type {number}
     * @memberof CommonResultListPositionVo
     */
    status: number;
    /**
     * 错误信息
     * @type {string}
     * @memberof CommonResultListPositionVo
     */
    message: string | null;
    /**
     * 
     * @type {Array<PositionVo>}
     * @memberof CommonResultListPositionVo
     */
    data: Array<PositionVo> | null;
}

export function CommonResultListPositionVoFromJSON(json: any): CommonResultListPositionVo {
    return CommonResultListPositionVoFromJSONTyped(json, false);
}

export function CommonResultListPositionVoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommonResultListPositionVo {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'status': json['status'],
        'message': json['message'],
        'data': (json['data'] === null ? null : (json['data'] as Array<any>).map(PositionVoFromJSON)),
    };
}

export function CommonResultListPositionVoToJSON(value?: CommonResultListPositionVo | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'status': value.status,
        'message': value.message,
        'data': (value.data === null ? null : (value.data as Array<any>).map(PositionVoToJSON)),
    };
}


