/* tslint:disable */
/* eslint-disable */
/**
 * 南师教室
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EmptyClassroomVo,
    EmptyClassroomVoFromJSON,
    EmptyClassroomVoFromJSONTyped,
    EmptyClassroomVoToJSON,
} from './';

/**
 * 
 * @export
 * @interface CommonResultListEmptyClassroomVo
 */
export interface CommonResultListEmptyClassroomVo {
    /**
     * 状态码
     * @type {number}
     * @memberof CommonResultListEmptyClassroomVo
     */
    status: number;
    /**
     * 错误信息
     * @type {string}
     * @memberof CommonResultListEmptyClassroomVo
     */
    message: string | null;
    /**
     * 
     * @type {Array<EmptyClassroomVo>}
     * @memberof CommonResultListEmptyClassroomVo
     */
    data: Array<EmptyClassroomVo> | null;
}

export function CommonResultListEmptyClassroomVoFromJSON(json: any): CommonResultListEmptyClassroomVo {
    return CommonResultListEmptyClassroomVoFromJSONTyped(json, false);
}

export function CommonResultListEmptyClassroomVoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommonResultListEmptyClassroomVo {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'status': json['status'],
        'message': json['message'],
        'data': (json['data'] === null ? null : (json['data'] as Array<any>).map(EmptyClassroomVoFromJSON)),
    };
}

export function CommonResultListEmptyClassroomVoToJSON(value?: CommonResultListEmptyClassroomVo | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'status': value.status,
        'message': value.message,
        'data': (value.data === null ? null : (value.data as Array<any>).map(EmptyClassroomVoToJSON)),
    };
}


