/* tslint:disable */
/* eslint-disable */
/**
 * 南师教室
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    UserFavoritesDto,
    UserFavoritesDtoFromJSON,
    UserFavoritesDtoFromJSONTyped,
    UserFavoritesDtoToJSON,
} from './';

/**
 * 
 * @export
 * @interface CommonResultListUserFavoritesDto
 */
export interface CommonResultListUserFavoritesDto {
    /**
     * 状态码
     * @type {number}
     * @memberof CommonResultListUserFavoritesDto
     */
    status: number;
    /**
     * 错误信息
     * @type {string}
     * @memberof CommonResultListUserFavoritesDto
     */
    message: string | null;
    /**
     * 
     * @type {Array<UserFavoritesDto>}
     * @memberof CommonResultListUserFavoritesDto
     */
    data: Array<UserFavoritesDto> | null;
}

export function CommonResultListUserFavoritesDtoFromJSON(json: any): CommonResultListUserFavoritesDto {
    return CommonResultListUserFavoritesDtoFromJSONTyped(json, false);
}

export function CommonResultListUserFavoritesDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommonResultListUserFavoritesDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'status': json['status'],
        'message': json['message'],
        'data': (json['data'] === null ? null : (json['data'] as Array<any>).map(UserFavoritesDtoFromJSON)),
    };
}

export function CommonResultListUserFavoritesDtoToJSON(value?: CommonResultListUserFavoritesDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'status': value.status,
        'message': value.message,
        'data': (value.data === null ? null : (value.data as Array<any>).map(UserFavoritesDtoToJSON)),
    };
}


