/* tslint:disable */
/* eslint-disable */
/**
 * 南师教室
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ShuttleRoute,
    ShuttleRouteFromJSON,
    ShuttleRouteFromJSONTyped,
    ShuttleRouteToJSON,
} from './';

/**
 * 
 * @export
 * @interface CommonResultListListShuttleRoute
 */
export interface CommonResultListListShuttleRoute {
    /**
     * 状态码
     * @type {number}
     * @memberof CommonResultListListShuttleRoute
     */
    status: number;
    /**
     * 错误信息
     * @type {string}
     * @memberof CommonResultListListShuttleRoute
     */
    message: string | null;
    /**
     * 
     * @type {Array<Array<ShuttleRoute>>}
     * @memberof CommonResultListListShuttleRoute
     */
    data: Array<Array<ShuttleRoute>> | null;
}

export function CommonResultListListShuttleRouteFromJSON(json: any): CommonResultListListShuttleRoute {
    return CommonResultListListShuttleRouteFromJSONTyped(json, false);
}

export function CommonResultListListShuttleRouteFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommonResultListListShuttleRoute {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'status': json['status'],
        'message': json['message'],
        'data': json['data'],
    };
}

export function CommonResultListListShuttleRouteToJSON(value?: CommonResultListListShuttleRoute | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'status': value.status,
        'message': value.message,
        'data': value.data,
    };
}


