/* tslint:disable */
/* eslint-disable */
/**
 * 南师教室
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    LoginVo,
    LoginVoFromJSON,
    LoginVoFromJSONTyped,
    LoginVoToJSON,
} from './';

/**
 * 
 * @export
 * @interface CommonResultLoginVo
 */
export interface CommonResultLoginVo {
    /**
     * 状态码
     * @type {number}
     * @memberof CommonResultLoginVo
     */
    status: number;
    /**
     * 错误信息
     * @type {string}
     * @memberof CommonResultLoginVo
     */
    message: string | null;
    /**
     * 
     * @type {LoginVo}
     * @memberof CommonResultLoginVo
     */
    data: LoginVo | null;
}

export function CommonResultLoginVoFromJSON(json: any): CommonResultLoginVo {
    return CommonResultLoginVoFromJSONTyped(json, false);
}

export function CommonResultLoginVoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommonResultLoginVo {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'status': json['status'],
        'message': json['message'],
        'data': LoginVoFromJSON(json['data']),
    };
}

export function CommonResultLoginVoToJSON(value?: CommonResultLoginVo | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'status': value.status,
        'message': value.message,
        'data': LoginVoToJSON(value.data),
    };
}


