/* tslint:disable */
/* eslint-disable */
/**
 * 南师教室
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    PageableResultTimetableVo,
    PageableResultTimetableVoFromJSON,
    PageableResultTimetableVoFromJSONTyped,
    PageableResultTimetableVoToJSON,
} from './';

/**
 * 
 * @export
 * @interface CommonResultPageableResultTimetableVo
 */
export interface CommonResultPageableResultTimetableVo {
    /**
     * 状态码
     * @type {number}
     * @memberof CommonResultPageableResultTimetableVo
     */
    status: number;
    /**
     * 错误信息
     * @type {string}
     * @memberof CommonResultPageableResultTimetableVo
     */
    message: string | null;
    /**
     * 
     * @type {PageableResultTimetableVo}
     * @memberof CommonResultPageableResultTimetableVo
     */
    data: PageableResultTimetableVo | null;
}

export function CommonResultPageableResultTimetableVoFromJSON(json: any): CommonResultPageableResultTimetableVo {
    return CommonResultPageableResultTimetableVoFromJSONTyped(json, false);
}

export function CommonResultPageableResultTimetableVoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommonResultPageableResultTimetableVo {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'status': json['status'],
        'message': json['message'],
        'data': PageableResultTimetableVoFromJSON(json['data']),
    };
}

export function CommonResultPageableResultTimetableVoToJSON(value?: CommonResultPageableResultTimetableVo | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'status': value.status,
        'message': value.message,
        'data': PageableResultTimetableVoToJSON(value.data),
    };
}


