/* tslint:disable */
/* eslint-disable */
/**
 * 南师教室
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    NoticeVo,
    NoticeVoFromJSON,
    NoticeVoFromJSONTyped,
    NoticeVoToJSON,
} from './';

/**
 * 
 * @export
 * @interface CommonResultNoticeVo
 */
export interface CommonResultNoticeVo {
    /**
     * 状态码
     * @type {number}
     * @memberof CommonResultNoticeVo
     */
    status: number;
    /**
     * 错误信息
     * @type {string}
     * @memberof CommonResultNoticeVo
     */
    message: string | null;
    /**
     * 
     * @type {NoticeVo}
     * @memberof CommonResultNoticeVo
     */
    data: NoticeVo | null;
}

export function CommonResultNoticeVoFromJSON(json: any): CommonResultNoticeVo {
    return CommonResultNoticeVoFromJSONTyped(json, false);
}

export function CommonResultNoticeVoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommonResultNoticeVo {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'status': json['status'],
        'message': json['message'],
        'data': NoticeVoFromJSON(json['data']),
    };
}

export function CommonResultNoticeVoToJSON(value?: CommonResultNoticeVo | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'status': value.status,
        'message': value.message,
        'data': NoticeVoToJSON(value.data),
    };
}


