/* tslint:disable */
/* eslint-disable */
/**
 * 南师教室
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    TimetableVo,
    TimetableVoFromJSON,
    TimetableVoFromJSONTyped,
    TimetableVoToJSON,
} from './';

/**
 * 
 * @export
 * @interface CommonResultListTimetableVo
 */
export interface CommonResultListTimetableVo {
    /**
     * 状态码
     * @type {number}
     * @memberof CommonResultListTimetableVo
     */
    status: number;
    /**
     * 错误信息
     * @type {string}
     * @memberof CommonResultListTimetableVo
     */
    message: string | null;
    /**
     * 
     * @type {Array<TimetableVo>}
     * @memberof CommonResultListTimetableVo
     */
    data: Array<TimetableVo> | null;
}

export function CommonResultListTimetableVoFromJSON(json: any): CommonResultListTimetableVo {
    return CommonResultListTimetableVoFromJSONTyped(json, false);
}

export function CommonResultListTimetableVoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommonResultListTimetableVo {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'status': json['status'],
        'message': json['message'],
        'data': (json['data'] === null ? null : (json['data'] as Array<any>).map(TimetableVoFromJSON)),
    };
}

export function CommonResultListTimetableVoToJSON(value?: CommonResultListTimetableVo | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'status': value.status,
        'message': value.message,
        'data': (value.data === null ? null : (value.data as Array<any>).map(TimetableVoToJSON)),
    };
}


