/* tslint:disable */
/* eslint-disable */
/**
 * 南师教室
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 空教室信息
 * @export
 * @interface EmptyClassroomVo
 */
export interface EmptyClassroomVo {
    /**
     * 
     * @type {number}
     * @memberof EmptyClassroomVo
     */
    id: number;
    /**
     * 教室代码
     * @type {string}
     * @memberof EmptyClassroomVo
     */
    jasdm: string;
    /**
     * 教室门牌号
     * @type {string}
     * @memberof EmptyClassroomVo
     */
    jsmph: string;
    /**
     * 上课座位数
     * @type {number}
     * @memberof EmptyClassroomVo
     */
    skzws: number;
    /**
     * 开始节次
     * @type {number}
     * @memberof EmptyClassroomVo
     */
    ksjc: number;
    /**
     * 结束节次
     * @type {number}
     * @memberof EmptyClassroomVo
     */
    jsjc: number;
    /**
     * 资源类型代码
     * @type {string}
     * @memberof EmptyClassroomVo
     */
    zylxdm: string;
}

export function EmptyClassroomVoFromJSON(json: any): EmptyClassroomVo {
    return EmptyClassroomVoFromJSONTyped(json, false);
}

export function EmptyClassroomVoFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmptyClassroomVo {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'jasdm': json['jasdm'],
        'jsmph': json['jsmph'],
        'skzws': json['skzws'],
        'ksjc': json['ksjc'],
        'jsjc': json['jsjc'],
        'zylxdm': json['zylxdm'],
    };
}

export function EmptyClassroomVoToJSON(value?: EmptyClassroomVo | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'jasdm': value.jasdm,
        'jsmph': value.jsmph,
        'skzws': value.skzws,
        'ksjc': value.ksjc,
        'jsjc': value.jsjc,
        'zylxdm': value.zylxdm,
    };
}


