/* tslint:disable */
/* eslint-disable */
/**
 * 南师教室
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 发现栏
 * @export
 * @interface GridVo
 */
export interface GridVo {
    /**
     * 名称
     * @type {string}
     * @memberof GridVo
     */
    text: string;
    /**
     * 图表
     * @type {string}
     * @memberof GridVo
     */
    imgUrl: string;
    /**
     * 跳转目标页面
     * @type {string}
     * @memberof GridVo
     */
    url?: string;
    /**
     * 点击执行方法
     * @type {string}
     * @memberof GridVo
     */
    method?: string;
    /**
     * 开放方法
     * @type {{ [key: string]: object | undefined; }}
     * @memberof GridVo
     */
    button?: { [key: string]: object | undefined; };
}

export function GridVoFromJSON(json: any): GridVo {
    return GridVoFromJSONTyped(json, false);
}

export function GridVoFromJSONTyped(json: any, ignoreDiscriminator: boolean): GridVo {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'text': json['text'],
        'imgUrl': json['imgUrl'],
        'url': !exists(json, 'url') ? undefined : json['url'],
        'method': !exists(json, 'method') ? undefined : json['method'],
        'button': !exists(json, 'button') ? undefined : json['button'],
    };
}

export function GridVoToJSON(value?: GridVo | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'text': value.text,
        'imgUrl': value.imgUrl,
        'url': value.url,
        'method': value.method,
        'button': value.button,
    };
}


