/* tslint:disable */
/* eslint-disable */
/**
 * 南师教室
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 登录信息
 * @export
 * @interface LoginVo
 */
export interface LoginVo {
    /**
     * 
     * @type {string}
     * @memberof LoginVo
     */
    token: string;
}

export function LoginVoFromJSON(json: any): LoginVo {
    return LoginVoFromJSONTyped(json, false);
}

export function LoginVoFromJSONTyped(json: any, ignoreDiscriminator: boolean): LoginVo {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'token': json['token'],
    };
}

export function LoginVoToJSON(value?: LoginVo | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'token': value.token,
    };
}


