/* tslint:disable */
/* eslint-disable */
/**
 * 南师教室
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 公告
 * @export
 * @interface NoticeVo
 */
export interface NoticeVo {
    /**
     * 公告id
     * @type {number}
     * @memberof NoticeVo
     */
    id: number;
    /**
     * 公告时间
     * @type {number}
     * @memberof NoticeVo
     */
    timestamp: number;
    /**
     * 公告日期
     * @type {string}
     * @memberof NoticeVo
     */
    date: string;
    /**
     * 公告内容
     * @type {string}
     * @memberof NoticeVo
     */
    text: string;
}

export function NoticeVoFromJSON(json: any): NoticeVo {
    return NoticeVoFromJSONTyped(json, false);
}

export function NoticeVoFromJSONTyped(json: any, ignoreDiscriminator: boolean): NoticeVo {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'timestamp': json['timestamp'],
        'date': json['date'],
        'text': json['text'],
    };
}

export function NoticeVoToJSON(value?: NoticeVo | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'timestamp': value.timestamp,
        'date': value.date,
        'text': value.text,
    };
}


