/* tslint:disable */
/* eslint-disable */
/**
 * 南师教室
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    TimetableVo,
    TimetableVoFromJSON,
    TimetableVoFromJSONTyped,
    TimetableVoToJSON,
} from './index';

/**
 * 
 * @export
 * @interface PageableResultTimetableVo
 */
export interface PageableResultTimetableVo {
    /**
     * 分页页号
     * @type {number}
     * @memberof PageableResultTimetableVo
     */
    page: number;
    /**
     * 分页大小
     * @type {number}
     * @memberof PageableResultTimetableVo
     */
    size: number;
    /**
     * 总页数
     * @type {number}
     * @memberof PageableResultTimetableVo
     */
    totalPage: number;
    /**
     * 总记录数
     * @type {number}
     * @memberof PageableResultTimetableVo
     */
    total: number;
    /**
     * 当前页记录
     * @type {Array<TimetableVo>}
     * @memberof PageableResultTimetableVo
     */
    records: Array<TimetableVo>;
}

export function PageableResultTimetableVoFromJSON(json: any): PageableResultTimetableVo {
    return PageableResultTimetableVoFromJSONTyped(json, false);
}

export function PageableResultTimetableVoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PageableResultTimetableVo {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'page': json['page'],
        'size': json['size'],
        'totalPage': json['totalPage'],
        'total': json['total'],
        'records': ((json['records'] as Array<any>).map(TimetableVoFromJSON)),
    };
}

export function PageableResultTimetableVoToJSON(value?: PageableResultTimetableVo | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'page': value.page,
        'size': value.size,
        'totalPage': value.totalPage,
        'total': value.total,
        'records': ((value.records as Array<any>).map(TimetableVoToJSON)),
    };
}


