/* tslint:disable */
/* eslint-disable */
/**
 * 南师教室
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 查询参数
 * @export
 * @interface SearchDto
 */
export interface SearchDto {
    /**
     * 星期
     * @type {string}
     * @memberof SearchDto
     */
    weekday?: SearchDtoWeekdayEnum;
    /**
     * 开始节次
     * @type {number}
     * @memberof SearchDto
     */
    ksjc: number;
    /**
     * 结束
     * @type {number}
     * @memberof SearchDto
     */
    jsjc: number;
    /**
     * 教学楼名称
     * @type {string}
     * @memberof SearchDto
     */
    jxlmc: string;
    /**
     * 资源类型代码
     * @type {string}
     * @memberof SearchDto
     */
    zylxdm: string;
    /**
     * 关键词
     * @type {string}
     * @memberof SearchDto
     */
    keyword: string;
}

export function SearchDtoFromJSON(json: any): SearchDto {
    return SearchDtoFromJSONTyped(json, false);
}

export function SearchDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'weekday': !exists(json, 'weekday') ? undefined : json['weekday'],
        'ksjc': json['ksjc'],
        'jsjc': json['jsjc'],
        'jxlmc': json['jxlmc'],
        'zylxdm': json['zylxdm'],
        'keyword': json['keyword'],
    };
}

export function SearchDtoToJSON(value?: SearchDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'weekday': value.weekday,
        'ksjc': value.ksjc,
        'jsjc': value.jsjc,
        'jxlmc': value.jxlmc,
        'zylxdm': value.zylxdm,
        'keyword': value.keyword,
    };
}

/**
* @export
* @enum {string}
*/
export enum SearchDtoWeekdayEnum {
    MON = 'MON',
    TUE = 'TUE',
    WED = 'WED',
    THU = 'THU',
    FRI = 'FRI',
    SAT = 'SAT',
    SUN = 'SUN'
}


