/* tslint:disable */
/* eslint-disable */
/**
 * 南师教室
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 校车时刻表
 * @export
 * @interface ShuttleRouteVo
 */
export interface ShuttleRouteVo {
    /**
     * 发车时间
     * @type {string}
     * @memberof ShuttleRouteVo
     */
    startTime: string;
    /**
     * 起点站
     * @type {string}
     * @memberof ShuttleRouteVo
     */
    startStation: string;
    /**
     * 终点站
     * @type {string}
     * @memberof ShuttleRouteVo
     */
    endStation: string;
}

export function ShuttleRouteVoFromJSON(json: any): ShuttleRouteVo {
    return ShuttleRouteVoFromJSONTyped(json, false);
}

export function ShuttleRouteVoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ShuttleRouteVo {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'startTime': json['startTime'],
        'startStation': json['startStation'],
        'endStation': json['endStation'],
    };
}

export function ShuttleRouteVoToJSON(value?: ShuttleRouteVo | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'startTime': value.startTime,
        'startStation': value.startStation,
        'endStation': value.endStation,
    };
}


