/* tslint:disable */
/* eslint-disable */
/**
 * 南师教室
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SimpleDataVoLong
 */
export interface SimpleDataVoLong {
    /**
     * 
     * @type {number}
     * @memberof SimpleDataVoLong
     */
    data: number;
}

export function SimpleDataVoLongFromJSON(json: any): SimpleDataVoLong {
    return SimpleDataVoLongFromJSONTyped(json, false);
}

export function SimpleDataVoLongFromJSONTyped(json: any, ignoreDiscriminator: boolean): SimpleDataVoLong {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': json['data'],
    };
}

export function SimpleDataVoLongToJSON(value?: SimpleDataVoLong | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': value.data,
    };
}


