/* tslint:disable */
/* eslint-disable */
/**
 * 南师教室
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SimpleDataVoBoolean
 */
export interface SimpleDataVoBoolean {
    /**
     * 
     * @type {boolean}
     * @memberof SimpleDataVoBoolean
     */
    data: boolean;
}

export function SimpleDataVoBooleanFromJSON(json: any): SimpleDataVoBoolean {
    return SimpleDataVoBooleanFromJSONTyped(json, false);
}

export function SimpleDataVoBooleanFromJSONTyped(json: any, ignoreDiscriminator: boolean): SimpleDataVoBoolean {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': json['data'],
    };
}

export function SimpleDataVoBooleanToJSON(value?: SimpleDataVoBoolean | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': value.data,
    };
}


