/* tslint:disable */
/* eslint-disable */
/**
 * 南师教室
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 时间表
 * @export
 * @interface TimetableVo
 */
export interface TimetableVo {
    /**
     * 
     * @type {number}
     * @memberof TimetableVo
     */
    id: number;
    /**
     * 教学楼名称
     * @type {string}
     * @memberof TimetableVo
     */
    jxlmc: string;
    /**
     * 教室门牌号
     * @type {string}
     * @memberof TimetableVo
     */
    jsmph: string;
    /**
     * 上课座位数
     * @type {number}
     * @memberof TimetableVo
     */
    skzws: number;
    /**
     * 星期
     * @type {string}
     * @memberof TimetableVo
     */
    weekday: TimetableVoWeekdayEnum;
    /**
     * 开始节次
     * @type {number}
     * @memberof TimetableVo
     */
    ksjc: number;
    /**
     * 结束节次
     * @type {number}
     * @memberof TimetableVo
     */
    jsjc: number;
    /**
     * 资源类型代码
     * @type {string}
     * @memberof TimetableVo
     */
    zylxdm: string;
    /**
     * 借用用途说明
     * @type {string}
     * @memberof TimetableVo
     */
    jyytms: string;
    /**
     * 课程名
     * @type {string}
     * @memberof TimetableVo
     */
    kcm: string;
}

export function TimetableVoFromJSON(json: any): TimetableVo {
    return TimetableVoFromJSONTyped(json, false);
}

export function TimetableVoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TimetableVo {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'jxlmc': json['jxlmc'],
        'jsmph': json['jsmph'],
        'skzws': json['skzws'],
        'weekday': json['weekday'],
        'ksjc': json['ksjc'],
        'jsjc': json['jsjc'],
        'zylxdm': json['zylxdm'],
        'jyytms': json['jyytms'],
        'kcm': json['kcm'],
    };
}

export function TimetableVoToJSON(value?: TimetableVo | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'jxlmc': value.jxlmc,
        'jsmph': value.jsmph,
        'skzws': value.skzws,
        'weekday': value.weekday,
        'ksjc': value.ksjc,
        'jsjc': value.jsjc,
        'zylxdm': value.zylxdm,
        'jyytms': value.jyytms,
        'kcm': value.kcm,
    };
}

/**
* @export
* @enum {string}
*/
export enum TimetableVoWeekdayEnum {
    MON = 'MON',
    TUE = 'TUE',
    WED = 'WED',
    THU = 'THU',
    FRI = 'FRI',
    SAT = 'SAT',
    SUN = 'SUN'
}


