/* tslint:disable */
/* eslint-disable */
/**
 * 南师教室
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 用户收藏
 * @export
 * @interface UserFavoritesDto
 */
export interface UserFavoritesDto {
    /**
     * 
     * @type {number}
     * @memberof UserFavoritesDto
     */
    id?: number;
    /**
     * 标题
     * @type {string}
     * @memberof UserFavoritesDto
     */
    title: string;
    /**
     * 星期
     * @type {string}
     * @memberof UserFavoritesDto
     */
    weekday: UserFavoritesDtoWeekdayEnum;
    /**
     * 开始节次
     * @type {number}
     * @memberof UserFavoritesDto
     */
    ksjc: number;
    /**
     * 结束节次
     * @type {number}
     * @memberof UserFavoritesDto
     */
    jsjc: number;
    /**
     * 地点
     * @type {string}
     * @memberof UserFavoritesDto
     */
    place: string;
    /**
     * 颜色
     * @type {string}
     * @memberof UserFavoritesDto
     */
    color: string;
    /**
     * 备注
     * @type {{ [key: string]: object | undefined; }}
     * @memberof UserFavoritesDto
     */
    remark: { [key: string]: object | undefined; };
}

export function UserFavoritesDtoFromJSON(json: any): UserFavoritesDto {
    return UserFavoritesDtoFromJSONTyped(json, false);
}

export function UserFavoritesDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserFavoritesDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'title': json['title'],
        'weekday': json['weekday'],
        'ksjc': json['ksjc'],
        'jsjc': json['jsjc'],
        'place': json['place'],
        'color': json['color'],
        'remark': json['remark'],
    };
}

export function UserFavoritesDtoToJSON(value?: UserFavoritesDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'title': value.title,
        'weekday': value.weekday,
        'ksjc': value.ksjc,
        'jsjc': value.jsjc,
        'place': value.place,
        'color': value.color,
        'remark': value.remark,
    };
}

/**
* @export
* @enum {string}
*/
export enum UserFavoritesDtoWeekdayEnum {
    MON = 'MON',
    TUE = 'TUE',
    WED = 'WED',
    THU = 'THU',
    FRI = 'FRI',
    SAT = 'SAT',
    SUN = 'SUN'
}


